data:
  class_path: src.dataset.base.ODDeepFakeDataModule
  init_args:
    test_datamodules:
    - class_path: src.dataset.ffpp.FFPPDataModule
      init_args:
        df_types: ['REAL','DF','FS','F2F','NT']
        compressions: ['c23']
        strategy: NORMAL
        augmentations: 
        - NONE
        force_random_speed: null
        data_dir: 'datasets/robustness/BW/1/'
        vid_ext: .avi
